# Убрали версию так как она устарела

services:
  obscur_backend:
    build: .
    container_name: obscur_backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - ./logs:/app/logs
    networks:
      - obscur_network

  # Nginx proxy for production (optional)
  nginx:
    image: nginx:alpine
    container_name: obscur_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - obscur_backend
    restart: unless-stopped
    networks:
      - obscur_network

networks:
  obscur_network:
    driver: bridge

volumes:
  logs: